name: Sync GitHub issues to Jira example

on:
  issues:
  issue_comment:

jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          component: 'WSL'
          webhook-url: ${{ secrets.JIRA_WEBHOOK_URL }}
